### ISSUE TITLE
ignored stations problems

### ISSUE THREAD

**Issue by ROMSY-SAN** [deg0nz/MMM-PublicTransportBerlin#23]
Hey again, i don't really know if i am too stupid or if it don't really work.

so i am living on the edge of fisherinsel. Around the corner I've got "Märkisches Museum"

so i wanted to ignore the busses which drive in the direction "Märkisches Museum" / "Ostbahnhof"
                                name: "Fischerinsel",
                                stationId: 900000100526,
                                hidden: false,
is working fine! 
But when i try ignoredStations i still see the busses which drive in direction Märkisches Museum / Ostbahnhof.
i tried 
ignoredStations: [900000100014, 900000100516, 900000120005, 900000120010, 900000261491],

and also this format:
 ignoredStations: ['900000100014', '900000100516', '900000120005', '900000120010', '900000261491'],

BUT: If i combine both: 
ignoredStations: [900000100014, 900000100516, 900000120005, 900000120010, 900000261491, '900000100014', '900000100516', '900000120005', '900000120010', '900000261491'],

at least every bus in direction Märkisches Museum disappears!

**Comment by deg0nz** [comment]
Your first issue is, because the `ignoredStations` function is not actually made for filtering directions but for filtering sub-stations around your main station. 
I'm not really sure, if I understand what you want to do... Do you want to remove a direction from the list? Or do you want do remove a sub-station from the list?

If you want the module to show only one direction:
In fact, this feature does not exist yet. We are currently discussing to implement a "Show only one direction" feature either in the API or the Mirror module in the forum right now. [You can follow the discussion here.](https://forum.magicmirror.builders/topic/832/mmm-publictransportberlin-public-transport-for-berlin-and-brandenburg-departures/57)

**Comment by ROMSY-SAN** [comment]
yep, totally misunderstood the function, sorry. 
"Show only one direction" was the feature that i am looking for +1

**Comment by deg0nz** [comment]
So, commit  8c5e69f implements this feature via the `directionStationId` variable. Some words about that:

After some tests, the data delivery of this feature seems not to be as reliable as the normal version. Also, please make sure you actually have the right stationId for the direction station. Please check your MagicMirror log for errors before reporting them. 
Additionally, more requestet results take more time for the request. So please make sure to keep your maxUnreachableDepartures and maxReachabledepartures low when using this feature. 

I also mentioned this in the readme. Closing this issue now.
