### ISSUE TITLE
MagicMirror - How to change the font? 

### ISSUE THREAD

**Issue by VinceBln** [deg0nz/MMM-PublicTransportBerlin#71]
We are beginners in Raspberry and Magic Mirror.
How can we change the font on modules in general? Is something like this possible?

Thx for every help we get. 

Vincent

**Comment by deg0nz** [comment]
Hi @VinceBln 

This is actually a question [for the forum.](https://forum.magicmirror.builders)

It has also already been answered there: https://forum.magicmirror.builders/topic/8758/change-fonts
And has been asked in various versions: https://forum.magicmirror.builders/search?term=change%20font&in=titles

I'm closing this issue since it is not related to my module. Please seek help about general questions in the forum - there are a lot of people that will help you :)
... and many questions have probably already been answered ;)
